version: '3.4'

services:
  apigateway.public:
    image: ${DOCKER_REGISTRY-}gatewayapi.public
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: GatewayApi.Public/Dockerfile

  apigateway.internal:
    image: ${DOCKER_REGISTRY-}gatewayapi.internal
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: GatewayApi.Internal/Dockerfile

  appointmentapi:
    image: ${DOCKER_REGISTRY-}appointmentapi
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: AppointmentApi/Dockerfile
