version: '3.4'

services:
  apigateway.public:
    image: ${DOCKER_REGISTRY-}gatewayapi.public
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: GatewayApi.Public/Dockerfile
    environment:
      - TZ=Europe/London

  apigateway.internal:
    image: ${DOCKER_REGISTRY-}gatewayapi.internal
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: GatewayApi.Internal/Dockerfile
    environment:
      - TZ=Europe/London

  appointmentapi:
    image: ${DOCKER_REGISTRY-}appointmentapi
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: AppointmentApi/Dockerfile
    depends_on:
      - appointmentapi-db
    environment:
      - TZ=Europe/London
  
  appointmentapi-db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "5003:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=2TnXSLhuAvN6xr42 
      - TZ=Europe/London
